name: Python

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Set up Python 3.11"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox

            - name: "Lint Python code"
              run: |
                  cd ${GITHUB_WORKSPACE}/python && tox -e lint
              env:
                  PLATFORM: ubuntu-latest

    py_success:
        name: "Python success"
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - run: echo "Python workflow completed successfully"
